# This workflow will install Python dependencies, run tests with multiple
# Python versions. We checkout the branch, install the package from scratch, then
# try and run the unit tests.

name: Build and run unit tests

on:
  push:
    branches: [ "main" ]
    paths:
    - 'p3analysis/**'
    - 'tests/**'
    - 'pyproject.toml'
    - 'MANIFEST.in'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'p3analysis/**'
    - 'tests/**'
    - 'pyproject.toml'
    - 'MANIFEST.in'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install p3analysis and its dependencies
      run: pip install --no-cache-dir './[dev]'
    - name: Run unittest
      run: python -m unittest discover -s tests --verbose
permissions: read-all
